# utils/event_utils.py

from urllib.parse import unquote_plus

from config import (
    CUSTOMER_UPLOAD_PREFIX,
    ORDER_UPLOAD_PREFIX,
    CUSTOMER_FILE_TYPE,
    ORDER_FILE_TYPE,
)


def extract_s3_event(event):
    """
    Extract the S3 bucket name and object key from
    the Lambda event generated by S3.

    Returns:
        tuple: (bucket_name, object_key)

    Raises:
        ValueError: If the event doesn't have the expected structure.
    """

    try:
        record = event["Records"][0]

        bucket_name = record["s3"]["bucket"]["name"]

        # S3 object keys can contain URL-encoded characters.
        # Decode them before using the key.
        object_key = unquote_plus(
            record["s3"]["object"]["key"]
        )

        return bucket_name, object_key

    except (KeyError, IndexError, TypeError) as exc:

        raise ValueError(
            f"Invalid S3 event received: {exc}"
        ) from exc


def identify_file_type(object_key):
    """
    Determine whether the uploaded file belongs to
    customers or orders based on the S3 folder.

    Example:
        uploads/customers/customers.csv
        -> customer

        uploads/orders/orders.csv
        -> order
    """

    if object_key.startswith(CUSTOMER_UPLOAD_PREFIX):
        return CUSTOMER_FILE_TYPE

    if object_key.startswith(ORDER_UPLOAD_PREFIX):
        return ORDER_FILE_TYPE

    raise ValueError(
        f"Unsupported S3 object location: {object_key}"
    )